**DOCUMENTACAO**

https://spark.apache.org/docs/3.0.2/api/sql/

In [0]:
%fs ls "FileStore/tables/"

path,name,size
dbfs:/FileStore/tables/arquivo_geral.csv,arquivo_geral.csv,73827

In [0]:
import pyspark.sql.functions as F

dados1 = [
         (1, "Anderson", 1000.00),
         (2, "Kennedy", 2000.00),
         (3, "Bruno", 2300.00),
         (4, "Maria", 2300.00),
         (5, "Eduardo", 2400.00),
         (6, "Mendes", 1900.00),
         (7, "Kethlyn", 1500.00),
         (8, "Thiago", 1800.00),
         (9, "Carla", 2100.00)
]

schema1 = ["id", "Nome", "Salario"]
spark.createDataFrame(data=dados1, schema=schema1).createOrReplaceTempView("funcionarios")

dados2 = [
    (1, "Delhi", "India"),
    (2, "Tamil Nadu", "India"),
    (3, "London", "UK"),
    (4, "Sydney", "Australia"),
    (8, "New York", "USA"),
    (9, "California", "USA"),
    (10, "New Jersey", "USA"),
    (11, "Texas", "USA"),
    (12, "Chicago", "USA")
]
schema2 = ["id", "local", "pais"]
spark.createDataFrame(data=dados2, schema=schema2).createOrReplaceTempView("localizacoes")

In [0]:
%sql
SHOW TABLES

database,tableName,isTemporary
default,tabela_covid,false
,funcionarios,true
,localizacoes,true

SELECT campos FROM tabela1 INNER JOIN tabela2 ON tabela1.coluna = tabela2.coluna

In [0]:
%sql
SELECT * FROM funcionarios INNER JOIN localizacoes ON funcionarios.id = localizacoes.id

id,Nome,Salario,id,local,pais
1,Anderson,1000.0,1,Delhi,India
2,Kennedy,2000.0,2,Tamil Nadu,India
3,Bruno,2300.0,3,London,UK
4,Maria,2300.0,4,Sydney,Australia
8,Thiago,1800.0,8,New York,USA
9,Carla,2100.0,9,California,USA

In [0]:
%sql
SELECT * FROM funcionarios LEFT OUTER JOIN localizacoes ON funcionarios.id = localizacoes.id

id,Nome,Salario,id,local,pais
1,Anderson,1000.0,1,Delhi,India
2,Kennedy,2000.0,2,Tamil Nadu,India
3,Bruno,2300.0,3,London,UK
4,Maria,2300.0,4,Sydney,Australia
5,Eduardo,2400.0,null,null,null
6,Mendes,1900.0,null,null,null
7,Kethlyn,1500.0,null,null,null
8,Thiago,1800.0,8,New York,USA
9,Carla,2100.0,9,California,USA

In [0]:
%sql
SELECT * FROM funcionarios RIGHT OUTER JOIN localizacoes ON funcionarios.id = localizacoes.id

id,Nome,Salario,id,local,pais
1,Anderson,1000.0,1,Delhi,India
2,Kennedy,2000.0,2,Tamil Nadu,India
3,Bruno,2300.0,3,London,UK
4,Maria,2300.0,4,Sydney,Australia
8,Thiago,1800.0,8,New York,USA
9,Carla,2100.0,9,California,USA
null,null,null,10,New Jersey,USA
null,null,null,11,Texas,USA
null,null,null,12,Chicago,USA